### ISSUE TITLE
thread.isAlive() not working

### ISSUE THREAD

**Issue by BinaryEnigma01** [munshigroup/kthread#3]
I don't know when this started happening, but at some point, KThread stopped working due to `AttributeError: 'KThread' object has no attribute 'isAlive'`
Since `is_alive()` appears to work, I "fixed" it by doing `main_thread.isAlive = main_thread.is_alive`
Three separate users have reported this happening on a project I'm working on, and I started being able to replicate it in a different machine.
Python version is 3.9.3, the users also had 3.9

**Comment by smunshi** [comment]
Hi BinaryEnigma01,

This repository is not actively monitored.  However, to address your issue, the `isAlive()` member of the base `Thread` class was deprecated and removed in Python 3.9.

Commit [bd20bb0](https://github.com/munshigroup/kthread/commit/bd20bb0ddd02fdd8ae0ee7f38c509f3e3e403b54) fixes this problem.

Thank you,
Sumit Munshi

The Munshi Group, Inc.
